### ISSUE TITLE
Improve weather response

### ISSUE THREAD

**Issue by jsunfutu** [Tiketti/las-palmas-hubot#1]
Would be super nice, if the weather report would also contain the "summary" (e.g. "summary": "Rain") in addition to the temperature.

To make the feature superduper nice, you could also pick the "icon" (e.g. "icon": "rain") from the JSON response and "translate" it to Flowdock supported emoji => :umbrella: (emoji cheat sheet here: http://www.webpagefx.com/tools/emoji-cheat-sheet/ )

**Comment by Tiketti** [comment]
Great idea. I'll add it to TODO list :)

**Comment by Tiketti** [comment]
Done 😄
